### ISSUE TITLE
Arch Linux root install on OpenZFS by Fork of Ubuntu on ZFS Scripts

### ISSUE THREAD

**Issue by Kodiman** [stevleibelt/arch-linux-live-cd-iso-with-zfs#14]
Hi, Also, note that Ubuntu has much more developed zfs on root install scripts (see the Sithuk link below). In the long term, would it save time and effort to fork and adapt the Ubuntu scripts to Arch Linux? Adapting the Sithuk scrips with help from the Kayvlim.  Is there anyone in the Arch Linux community who knows how to do this? Would this benefit the community to keep up with Ubuntu? Replies are welcome. Thanks

https://github.com/Sithuk/ubuntu-server-zfsbootmenu

See this link for information and syntax about Arch Linux on ZFS...
https://wiki.archlinux.org/title/User:Kayvlim/Install_UEFI_and_BIOS_compatible_Arch_Linux_with_Encrypted_ZFS_and_ZFSBootMenu#Swap...

**Comment by stevleibelt** [comment]
@Kodiman thanks for your link and the information.

I can not answer your question. I am not deep into the arch community so I have no idea if there is a big community around archzfs. I hope so but since I've started, I could not find scripts for my need so I've started my project.

I will try to have a look on the Sithuk repository you've mentioned to check how much work it would be to join forces and create a script that works on ubuntu and arch.

How are your skills? Do you need something that does not exist in [here](https://github.com/stevleibelt/arch-linux-configuration)?
Can you tell me, in your words, what the Sithuk script has?

Best regards,
Stev

**Comment by stevleibelt** [comment]
I will close this issue for lack of response by @Kodiman
